apiVersion: v1
kind: Service
metadata:
  name: your-app-service
spec:
  type: NodePort
  selector:
    app: your-app
  ports:
    - protocol: TCP
      port: 8090
      targetPort: 8090
      nodePort: 30007
